name: build
on:
  push:
    branches:
      - main
    paths:
      - src/**.Dockerfile
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build images and push to docker hub
        run: ${GITHUB_WORKSPACE}/docker-build-and-push.bash
        shell: bash
        env:
          TOKEN_DOCKER: ${{ secrets.TOKEN_DOCKER }}
