name: template
on:
  schedule:
    - cron: '0 0,6,12,18 * * *' #every 6 hours
  workflow_dispatch:

jobs:
  template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN_GITHUB }}

      - name: Build templates and push changes
        run: build-templates.bash
        shell: bash

      - name: Commit changes
        run: commit-changes.bash
        shell: bash
